[package]
name = "benchbencher"
version = "0.1.0"
authors = ["Alexander Theißen <alex.theissen@me.com>"]
edition = "2018"
resolver = "2"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
